"""Change unique and index to phone column

Revision ID: efc9ed40ccdc
Revises: 
Create Date: 2024-09-26 22:38:57.795339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc9ed40ccdc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visitor_access_code', table_name='visitor')
    op.create_index(op.f('ix_visitor_phone'), 'visitor', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_phone'), table_name='visitor')
    op.create_index('ix_visitor_access_code', 'visitor', ['access_code'], unique=True)
    # ### end Alembic commands ###
